name: Publish podspecs to CocoaPods

on:
  push:
    tags:
      - "*"

jobs:
  publish-dependencies:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Deploy to Cocoapods Trunk
        run: |
          set -euo pipefail
          pod trunk push --allow-warnings BeyondIdentityCoreSDK.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

  publish-embedded:
    needs: publish-dependencies
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Deploy to Cocoapods Trunk
        run: |
          sleep 900
          set -euo pipefail
          pod repo update
          pod trunk push --allow-warnings BeyondIdentityEmbedded.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
