# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build & Publish DocC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Documentation
        run: xcodebuild docbuild -derivedDataPath Documentation -destination 'platform=iOS Simulator,name=iPhone 14' -scheme BeyondIdentitySDKs

      - name: Transform for Static Hosting
        run: $(xcrun --find docc) process-archive transform-for-static-hosting Documentation/Build/Products/Debug-iphonesimulator/BeyondIdentityEmbedded.doccarchive --hosting-base-path "${{ secrets.HOSTING_BASE_PATH }}" --output-path docs

      - name: Publish Swift Doc
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
