name: Swift CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: xcodebuild clean build -project BISDK.xcodeproj -scheme BISDK CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO  
  test-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: xcodebuild test -project BISDK.xcodeproj -scheme BISDK -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11,OS=14.4" -verbose

